NextProd/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import (
	home_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls', namespace='core')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import (
	home_view,
)


app_name = "core"
urlpatterns = [
    path('', home_view, name='home'),
]

core/models.py
from django.db import models
from PIL import Image



class BackgroundIntro(models.Model):
	header	= models.CharField(max_length=300)
	description = models.CharField(max_length=750)
	background_image = models.ImageField(upload_to='images')

	def __str__(self):
		return self.header


class NextService(models.Model):
	service_name = models.CharField(max_length=100,blank=True, null=True)
	image =  models.ImageField(upload_to='images')
	description = models.CharField(max_length=255, null=True)


	def __str__(self):
		return self.service_name


class FilmProduction(models.Model):
	image = models.ImageField(upload_to='images')
	service_name = models.CharField(max_length=100, null=True)


	def __str__(self):
		return self.service_name

class Projects(models.Model):
	clients = models.IntegerField(default=1)
	projects = models.IntegerField(default=1)
	hours_of_support = models.IntegerField(default=1)
	hard_work = models.IntegerField(default=1)
	
	def __str__(self):
		return str(self.clients) + "--" + str(self.projects)

class RadioAdverts(models.Model):
	image = models.ImageField(upload_to='images')
	title = models.CharField(max_length=100, null=True)
	description = models.CharField(max_length=100, null=True)


	def __str__(self):
		return self.title

class OurClients(models.Model):
	image = models.ImageField(upload_to='images')
	name = models.CharField(max_length=100, null=True)


	def __str__(self):
		return self.name

class Testimonials(models.Model):
	client_image = models.ImageField(upload_to='images')
	client_name = models.CharField(max_length=200, null=True)
	client_profession = models.CharField(max_length=100, null=True)
	comment = models.TextField(null=True,blank=True)

	def __str__(self):
		return self.client_name + "-" + self.client_profession

class Team(models.Model):
	image = models.ImageField(upload_to='images')
	name = models.CharField(max_length=200, null=True)
	position = models.CharField(max_length=200, null=True)
	twitter = models.CharField(max_length=300, blank=True, null=True)
	facebook = models.CharField(max_length=300, blank=True, null=True)
	gmail = models.CharField(max_length=300, blank=True, null=True)
	linked = models.CharField(max_length=300, blank=True, null=True)

	def __str__(self):
		return self.name + "-" + self.position

class Contact(models.Model):
	sender = models.CharField(max_length=200, null=True)
	subject = models.CharField(max_length=200, null=True)
	message = models.TextField(max_length=500, null=True)
	email = models.EmailField(max_length=255, null=True)

	def __str__(self):
		return self.sender + "-" + self.subject

core/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . models import (
	BackgroundIntro,
	NextService,
	FilmProduction,
	Projects,
	RadioAdverts,
	OurClients,
	Testimonials,
	Team,
)




def home_view(request):
	intro = BackgroundIntro.objects.all()
	services = NextService.objects.all()
	production = FilmProduction.objects.all()
	projects = Projects.objects.all()
	adverts = RadioAdverts.objects.all()
	clients = OurClients.objects.all()
	testimonial = Testimonials.objects.all()
	teams = Team.objects.all()
	context = {
			"intro":intro,
			"services":services,
			"production":production,
			"projects":projects,
			"adverts":adverts,
			"clients":clients,
			"tests":testimonial,
			"teams":teams,
	}
	return render(request, "core/home.html", context)

core/templates/core/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<main id="main">

    <!-- ======= Featured Services Section Section ======= -->
    <section id="featured-services">
      <div class="container">
        <div class="row">

          <div class="col-lg-12 box">
            <h4 class="title"><a href=""><span>Welcome to</span>  <span class="next">Next Productions Ltd</span></a></h4>
            <p class="description">Next Productin is a subsidiary of NextMedia Services. Next Production operations encompass motion picture production, acquisition, and distribution; television production, acquisition, and distribution; television networks; digital content creation and distributionNext Productions Ltd has long specialized in the delivery of quality content for Photography,
            TV, Radio and print productions under varying conditions, budgets and within short time frames.
            We work with NGOs, Government bodies, corporations and advertising agencies
            to produce a wide range of media and video production options.
          </p>
          </div>

        </div>
      </div>
    </section><!-- End Featured Services Section -->

    <!-- ======= About Us Section ======= -->
    <section id="about">
      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h3>Our Services</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </header>

        <div class="row about-cols">
          {% for service in services %}
          <div class="col-md-4" data-aos="fade-up" data-aos-delay="100">
            <div class="about-col">
              <div class="img">
                <img src="{{service.image.url}}" alt="" class="img-fluid" style="height: 232px; width: 100%;">
              </div>
              <h2 class="title"><a href="">{{service.service_name}}</a></h2>
              <p>
                {{service.description}}
              </p>
            </div>
          </div>
          {% endfor %}

        </div>

      </div>
    </section><!-- End About Us Section -->

    <!-- ======= Services Section ======= -->
    <section id="services">
      <div class="container" data-aos="fade-up">

        <header class="section-header wow fadeInUp">
          <h3>Film Production</h3>
          <p>Laudem latine persequeris id sed, ex fabulas delectus quo. No vel partiendo abhorreant vituperatoribus, ad pro quaestio laboramus. Ei ubique vivendum pro. At ius nisl accusam lorenta zanos paradigno tridexa panatarel.</p>
        </header>

        <div class="row">
          {% for item in production %}
          <div class="col-lg-4 col-md-6 box" data-aos="fade-up" data-aos-delay="100">
            <!-- <div class="icon"><i class="ion-ios-analytics-outline"></i></div> -->
            <div class="img">
                <img src="{{item.image.url}}" style="height: 236px; width: 100%;" alt="" class="img-fluid">
            </div>
            <div class="row">
              <h4 class="title"><a href="">{{item.service_name}}</a></h4>
            </div>
            
          </div>
          {% endfor %}
        </div>

      </div>
    </section><!-- End Services Section -->

    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action">
      <div class="container text-center" data-aos="zoom-in">
        <h3>Call To Action</h3>
        <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a class="cta-btn" href="#">Call To Action</a>
      </div>
    </section><!-- End Call To Action Section -->

    

    <!-- ======= Facts Section ======= -->
    <section id="facts">
      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h3>PROJECTS</h3>
          <p>Projects worked on by Next Production since its inception</p>
        </header>

        {% for project in projects %}
        <div class="row counters">
          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">{{project.clients}}</span>
            <p>Clients</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">{{project.projects}}</span>
            <p>Projects</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">{{project.hours_of_support}}</span>
            <p>Hours Of Support</p>
          </div>

          <div class="col-lg-3 col-6 text-center">
            <span data-toggle="counter-up">{{project.hard_work}}</span>
            <p>Hard Workers</p>
          </div>

        </div>
        {% endfor %}

        <!-- <div class="facts-img">
          <img src="{% static 'assets/img/facts-img.png' %}" alt="" class="img-fluid">
        </div> -->

      </div>
    </section><!-- End Facts Section -->

    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="section-bg">
      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h3 class="section-title">RADIO ADVERTS</h3>
        </header>

        <div class="row" data-aos="fade-up" data-aos-delay="100"">
      <div class=" col-lg-12">
          <ul id="portfolio-flters">
            <li data-filter="*" class="filter-active">All</li>
            <li data-filter=".filter-app">App</li>
            <li data-filter=".filter-card">Card</li>
            <li data-filter=".filter-web">Web</li>
          </ul>
        </div>
      </div>

      <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
        {% for advert in adverts %}
        <div class="col-lg-4 col-md-6  portfolio-item filter-app">
          <div class="portfolio-wrap">
            <figure>
              <img src="{{advert.image.url}}" class="img-fluid" alt="">
              <a href="{{advert.image.url}}" data-lightbox="portfolio" data-title="App 1" class="link-preview"><i class="ion ion-eye"></i></a>
              <a href="portfolio-details.html" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
            </figure>

            <div class="portfolio-info">
              <h4><a href="portfolio-details.html">{{advert.title}}</a></h4>
              <p>{{advert.title}}</p>
            </div>
          </div>
        </div>
        
        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
          <div class="portfolio-wrap">
            <figure>
              <img src="{{advert.image.url}}" class="img-fluid" alt="">
              <a href="{{advert.image.url}}" class="link-preview venobox" data-gall="portfolioGallery" title="Web 3"><i class="ion ion-eye"></i></a>
              <a href="portfolio-details.html" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
            </figure>

            <div class="portfolio-info">
              <h4><a href="portfolio-details.html">{{advert.title}}</a></h4>
              <p>{{advert.description}}</p>
            </div>
          </div>
        </div>

  

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
          <div class="portfolio-wrap">
            <figure>
              <img src="{{advert.image.url}}" class="img-fluid" alt="">
              <a href="{{advert.image.url}}" class="link-preview venobox" data-gall="portfolioGallery" title="Card 2"><i class="ion ion-eye"></i></a>
              <a href="portfolio-details.html" class="link-details" title="More Details"><i class="ion ion-android-open"></i></a>
            </figure>

            <div class="portfolio-info">
              <h4><a href="portfolio-details.html">{{advert.title}}</a></h4>
              <p>{{advert.description}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
       
      </div>

      </div>
    </section><!-- End Portfolio Section -->

    <!-- ======= Our Clients Section ======= -->
    <section id="clients">
      <div class="container" data-aos="zoom-in">

        <header class="section-header">
          <h3>Our Clients</h3>
        </header>

        <div class="owl-carousel clients-carousel">
          {% for client in clients %}
          <img src="{{client.image.url}}" alt="">
          {% endfor %}
        </div>

      </div>
    </section><!-- End Our Clients Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="section-bg">
      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h3>Testimonials</h3>
        </header>

        <div class="owl-carousel testimonials-carousel">
          {% for item in tests %}
          <div class="testimonial-item">
            <img src="{{item.client_image.url}}" class="testimonial-img" alt="">
            <h3>{{item.client_name}}</h3>
            <h4>{{item.client_profession}}</h4>
            <p>
              <img src="{% static 'assets/img/quote-sign-left.png' %}" class="quote-sign-left" alt="">
                  {{item.comment}}
              <img src="{% static 'assets/img/quote-sign-right.png' %}" class="quote-sign-right" alt="">
            </p>
          </div>
          {% endfor %}

        </div>

      </div>
    </section><!-- End Testimonials Section -->

    <!-- ======= Team Section ======= -->
    <section id="team">
      <div class="container" data-aos="fade-up">
        <div class="section-header">
          <h3>Team</h3>
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>

        <div class="row">
          {% for item in teams %}
          <div class="col-lg-3 col-md-6">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <img src="{{item.image.url}}" class="img-fluid" alt="">
              <div class="member-info">
                <div class="member-info-content">
                  <h4>{{item.name}}</h4>
                  <span>{{item.position}}</span>
                  <div class="social">
                    <a href="{{item.twitter}}"><i class="fa fa-twitter"></i></a>
                    <a href="{{item.facebook}}"><i class="fa fa-facebook"></i></a>
                    <a href="{{item.gmail}}"><i class="fa fa-google-plus"></i></a>
                    <a href="{{item.linked}}"><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          
        </div>

      </div>
    </section><!-- End Team Section -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h3>Contact Us</h3>
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>

        <div class="row contact-info">

          <div class="col-md-4">
            <div class="contact-address">
              <i class="ion-ios-location-outline"></i>
              <h3>Address</h3>
              <address>Plot 108 Nagguru Summut View, Kampala</address>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-phone">
              <i class="ion-ios-telephone-outline"></i>
              <h3>Phone Number</h3>
              <p><a href="tel:+155895548855">+256 789 55488 55</a></p>
            </div>
          </div>

          <div class="col-md-4">
            <div class="contact-email">
              <i class="ion-ios-email-outline"></i>
              <h3>Email</h3>
              <p><a href="mailto:info@example.com">info@nextproduction.com</a></p>
            </div>
          </div>

        </div>

        <div class="form">
          <form action="forms/contact.php" method="post" role="form" class="php-email-form">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validate"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validate"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validate"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validate"></div>
            </div>
            <div class="mb-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div>

      </div>
    </section><!-- End Contact Section -->

  </main>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Next Production</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/next_production.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'snippets/header.html' %}
  <!-- End Header -->

  <!-- ======= Intro Section ======= -->
  {% include 'snippets/intro_section.html' %}
  <!-- End Intro Section -->

  <!-- Start #main -->
    {% block content %}
    {% endblock content %}  <!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'snippets/footer.html' %}
  <!-- End Footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/snippets/footer.html
{% load static %}
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>NEXT PRODOUCTION</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <!-- <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Home</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">About us</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Services</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#">Privacy policy</a></li>
            </ul> -->
          </div>
          

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <!-- <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form> -->
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              Plot 108 Nagguru <br>
              Nagguru Summut View<br>
              Kampala <br>
              <strong>Phone:</strong> +256 7589 554 55<br>
              <strong>Email:</strong> nextproduction@nextmedia.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>NextProduction</strong>. 
      </div>
      <div class="credits">
        <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=BizPage
      -->
        Designed by <a href="#">Bukenya Lukman</a>
      </div>
    </div>
  </footer>

templates/snippets/header.html
{% load static %}
<header id="header" class="fixed-top header-transparent">
    <div class="container-fluid">

      <div class="row justify-content-center">
        <div class="col-xl-11 d-flex align-items-center">
          <h1 class="logo mr-auto"><a href="index.html"><img src="{% static 'assets/img/next_production.png' %}" style="width: 100px; height: 200px;"></a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

          <nav class="nav-menu d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'core:home' %}">Home</a></li>
              <li><a href="#about">Services</a></li>
              <li><a href="#services">Film Production</a></li>
              <li><a href="#facts">Projects</a></li>
              <li><a href="#portfolio">Radio Adverts</a></li>
              <li><a href="#team">Team</a></li>
              <!-- li class="drop-down"><a href="">Drop Down</a>
                <ul>
                  <li><a href="#">Drop Down 1</a></li>
                  <li><a href="#">Drop Down 3</a></li>
                  <li><a href="#">Drop Down 4</a></li>
                  <li><a href="#">Drop Down 5</a></li>
                </ul>
              </li> -->
              <li><a href="#contact">Contact Us</a></li>

            </ul>
          </nav><!-- .nav-menu -->
        </div>
      </div>

    </div>
  </header>

templates/snippets/intro_section.html
{% load static %}
<section id="intro">
    <div class="intro-container">
      
      <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        

        <div class="carousel-inner" role="listbox">
          {% for item in intro %}
          <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}" style="background-image: url({{item.background_image.url}})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">{{item.header}}</h2>
                <p class="animate__animated animate__fadeInUp">{{item.description}}</p>
                <a href="#featured-services" class="btn-get-started scrollto animate__animated animate__fadeInUp">Learn More</a>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- <div class="carousel-item" style="background-image: url({% static 'assets/img/intro-carousel/2.jpeg' %})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">At the Epitome of Quality</h2>
                <p class="animate__animated animate__fadeInUp">Operation of studio facilities; and development of new entertainment products, services and technologies.</p>
                <a href="#featured-services" class="btn-get-started scrollto animate__animated animate__fadeInUp">Learn More</a>
              </div>
            </div>
          </div> -->

          <!-- <div class="carousel-item" style="background-image: url({% static 'assets/img/intro-carousel/3.jpeg' %})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Production House at One Stop Center</h2>
                <p class="animate__animated animate__fadeInUp">Next Production Television operates dozens of wholly-owned or joint-venture production companies around East Africa. Next Production  organizations include Next Pictures, NBS Television Pictures</p>
                <a href="#featured-services" class="btn-get-started scrollto animate__animated animate__fadeInUp">Learn More</a>
              </div>
            </div>
          </div> -->

          <!-- <div class="carousel-item" style="background-image: url({% static 'assets/img/intro-carousel/4.jpeg' %})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Never Like Before</h2>
                <p class="animate__animated animate__fadeInUp">Next Production Television operates dozens of wholly-owned or joint-venture production companies around East Africa. Next Production  organizations include Next Pictures, NBS Television Pictures</p>
                <a href="#featured-services" class="btn-get-started scrollto animate__animated animate__fadeInUp">Learn More</a>
              </div>
            </div>
          </div> -->

          <!-- <div class="carousel-item" style="background-image: url({% static 'assets/img/intro-carousel/3.jpg' %})">
            <div class="carousel-container">
              <div class="container">
                <h2 class="animate__animated animate__fadeInDown">Our Diverse Production</h2>
                <p class="animate__animated animate__fadeInUp">We offer a vast portfolio of modern characters and stories that connect with audiences from 3 to 70 years old. From bands of badass girl-bosses to tribes of evil geniuses, we reflect modern culture and welcome all to our family of misfits, heroes, upstarts and icons. Through this we build global franchises that are a reflection of our wonderfully diverse and complex consumers.</p>
                <a href="#featured-services" class="btn-get-started scrollto animate__animated animate__fadeInUp">Learn More</a>
              </div>
            </div>
          </div> -->





        </div>
        
        <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        
      </div>
      
    </div>
  </section>